### ISSUE TITLE
multiple issues with Suggestion cog

### ISSUE THREAD

**Issue by cj2tech** [brandons209/Script-Generator-Cog#33]
Unable to make a suggestion when loading the 3.5 update

issues 1: it can't Idk if it's just me or but I can't get the cog to recognize default emojis
`[p]setsuggest downemoji 👎` comes back with `Emoji "👎" not found.`

issues 2: Unable to use `[p]suggest <suggestion>`
bot reply `Error in command 'suggest'. Check your console or logs for details.`
console displays 

> [ERROR] red: Exception in command 'suggest'
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/cogs/CogManager/cogs/suggestion/suggestion.py", line 86, in suggest
    icon_url=ctx.author.avatar_url,
             ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Member' object has no attribute 'avatar_url'

**Comment by brandons209** [comment]
Unfortunately, the repo currently is not updated to post version 3.5 for redbot, so the cog will not work. I'm currently about 65% done with the update, follow the update-3.5 branch for updates! Thanks for your patience.

**Comment by cj2tech** [comment]
Dope nice to know you still working on it tho Keep it up!
